/// Decides what never enters the history. Getting this wrong leaks
/// passwords, so it errs on the side of leaving things out.
///
/// Password managers and other careful apps mark sensitive copies with
/// types from the nspasteboard.org conventions; every clipboard manager is
/// expected to honour them. Apps the user excludes are skipped whatever
/// they copy.
struct ClipboardPrivacy: Sendable {
    /// Bundle identifiers whose copies are never recorded.
    var excludedApps: Set<String>

    /// Password managers and the system's password apps, left out from the
    /// start. The user can edit the list.
    static let defaultExcludedApps: Set<String> = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.apple.keychainaccess",
        "com.apple.Passwords",
        "com.lastpass.LastPass",
        "com.dashlane.Dashlane",
        "org.keepassxc.keepassxc",
        "in.sinew.Enpass-Desktop",
    ]

    /// Types that mark a copy as not for keeping (nspasteboard.org), plus
    /// older marker types some apps still use.
    static let markerTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "com.typeit4me.clipping",
        "net.antelle.keeweb",
    ]

    enum Verdict: Equatable {
        case keep
        /// Marked as concealed, transient or generated by the app itself.
        case marked
        /// Copied in an app the user excluded.
        case excludedApp
    }

    /// - Parameters:
    ///   - types: every type on the pasteboard, not only the kept ones.
    ///   - sourceBundleID: the app the copy came from, when known.
    func verdict(types: [String], sourceBundleID: String?) -> Verdict {
        if types.contains(where: Self.markerTypes.contains) { return .marked }
        if let sourceBundleID, excludedApps.contains(sourceBundleID) { return .excludedApp }
        return .keep
    }
}
