import AppKit
import Foundation
import Testing

@Suite struct ClipboardPrivacyTests {
    let privacy = ClipboardPrivacy(excludedApps: ClipboardPrivacy.defaultExcludedApps)

    @Test func markedCopiesAreNeverKept() {
        for marker in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                       "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"] {
            #expect(privacy.verdict(types: ["public.utf8-plain-text", marker], sourceBundleID: "com.apple.Safari") == .marked,
                    "\(marker)")
        }
    }

    @Test func passwordManagersAreExcludedFromTheStart() {
        #expect(privacy.verdict(types: ["public.utf8-plain-text"], sourceBundleID: "com.1password.1password") == .excludedApp)
        #expect(privacy.verdict(types: ["public.utf8-plain-text"], sourceBundleID: "com.apple.Passwords") == .excludedApp)
        #expect(privacy.verdict(types: ["public.utf8-plain-text"], sourceBundleID: "com.apple.Safari") == .keep)
        #expect(privacy.verdict(types: ["public.utf8-plain-text"], sourceBundleID: nil) == .keep)
    }
}

@MainActor
@Suite struct ClipboardHistoryTests {
    func text(_ string: String, pinned: Bool = false) -> ClipboardItem {
        ClipboardItem(date: .now, contents: [NSPasteboard.PasteboardType.string.rawValue: Data(string.utf8)], isPinned: pinned)
    }

    @Test func newestComesFirstAndRepeatsMoveUp() {
        let history = ClipboardHistory()
        history.add(text("a"))
        history.add(text("b"))
        history.add(text("a"))
        #expect(history.items.compactMap(\.text) == ["a", "b"])
    }

    @Test func theLimitDropsTheOldestButNeverPinned() {
        let history = ClipboardHistory(items: [text("pinned", pinned: true)], limit: 2)
        for word in ["1", "2", "3"] { history.add(text(word)) }
        #expect(history.items.compactMap(\.text) == ["3", "2", "pinned"])
        history.limit = 1
        #expect(history.items.compactMap(\.text) == ["3", "pinned"])
    }

    @Test func aRepeatedPinnedItemStaysPinned() {
        let history = ClipboardHistory(items: [text("keep", pinned: true)])
        history.add(text("keep"))
        #expect(history.items.count == 1 && history.items[0].isPinned)
    }

    @Test func clearingKeepsPinned() {
        let history = ClipboardHistory(items: [text("keep", pinned: true), text("go")])
        history.clear()
        #expect(history.items.compactMap(\.text) == ["keep"])
    }
}

/// Runs against a private pasteboard, never the user's.
@MainActor
@Suite struct ClipboardCaptureTests {
    let pasteboard = NSPasteboard(name: .init("KeyBridgeTests-\(UUID().uuidString)"))
    let defaults: UserDefaults = {
        let suite = "ClipboardCaptureTests.\(UUID().uuidString)"
        return UserDefaults(suiteName: suite)!
    }()

    func copy(_ text: String, extra: [String] = []) {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for type in extra { item.setData(Data(), forType: .init(type)) }
        pasteboard.writeObjects([item])
    }

    @Test func offByDefaultAndRecordsNothing() {
        let clipboard = ClipboardController(pasteboard: pasteboard, defaults: defaults)
        #expect(!clipboard.isEnabled)
        copy("hello")
        clipboard.checkNow()
        #expect(clipboard.history.items.isEmpty)

        clipboard.isEnabled = true
        clipboard.checkNow()
        #expect(clipboard.history.items.isEmpty, "Only copies made while it is on")
    }

    @Test func textIsCapturedAndConcealedIsNot() {
        let clipboard = ClipboardController(pasteboard: pasteboard, defaults: defaults)
        clipboard.isEnabled = true
        copy("hello")
        clipboard.checkNow()
        #expect(clipboard.history.items.first?.text == "hello")

        copy("secret", extra: ["org.nspasteboard.ConcealedType"])
        clipboard.checkNow()
        #expect(!clipboard.history.items.contains { $0.text == "secret" })
    }

    @Test func imagesAndFilesKeepTheirType() throws {
        let clipboard = ClipboardController(pasteboard: pasteboard, defaults: defaults)
        clipboard.isEnabled = true

        pasteboard.clearContents()
        let image = NSImage(size: NSSize(width: 4, height: 4))
        pasteboard.writeObjects([image])
        clipboard.checkNow()
        #expect(clipboard.history.items.first?.kind == .image)

        pasteboard.clearContents()
        pasteboard.writeObjects([URL(fileURLWithPath: "/tmp/report.pdf") as NSURL])
        clipboard.checkNow()
        #expect(clipboard.history.items.first?.kind == .file)
        #expect(clipboard.history.items.first?.fileURL?.lastPathComponent == "report.pdf")
    }

    @Test func theExclusionListIsEditableAndSaved() {
        let clipboard = ClipboardController(pasteboard: pasteboard, defaults: defaults)
        clipboard.exclude("com.apple.Safari")
        #expect(ClipboardController(pasteboard: pasteboard, defaults: defaults).excludedApps.contains("com.apple.Safari"))
        clipboard.include("com.1password.1password")
        #expect(!clipboard.excludedApps.contains("com.1password.1password"))
        clipboard.resetExcludedApps()
        #expect(Set(clipboard.excludedApps) == ClipboardPrivacy.defaultExcludedApps)
    }
}
