import AppKit
import Foundation
import Testing

@Suite struct ClipboardPrivacyTests {
    let privacy = ClipboardPrivacy(excludedApps: ClipboardPrivacy.defaultExcludedApps)

    @Test func markedCopiesAreNeverKept() {
        for marker in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                       "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"] {
            #expect(privacy.verdict(types: ["public.utf8-plain-text", marker], sourceBundleID: "com.apple.Safari") == .marked,
                    "\(marker)")
        }
    }

    @Test func passwordManagersAreExcludedFromTheStart() {
        #expect(privacy.verdict(types: ["public.utf8-plain-text"], sourceBundleID: "com.1password.1password") == .excludedApp)
        #expect(privacy.verdict(types: ["public.utf8-plain-text"], sourceBundleID: "com.apple.Passwords") == .excludedApp)
        #expect(privacy.verdict(types: ["public.utf8-plain-text"], sourceBundleID: "com.apple.Safari") == .keep)
        #expect(privacy.verdict(types: ["public.utf8-plain-text"], sourceBundleID: nil) == .keep)
    }
}

@MainActor
@Suite struct ClipboardHistoryTests {
    func text(_ string: String, pinned: Bool = false) -> ClipboardItem {
        ClipboardItem(date: .now, contents: [NSPasteboard.PasteboardType.string.rawValue: Data(string.utf8)], isPinned: pinned)
    }

    @Test func newestComesFirstAndRepeatsMoveUp() {
        let history = ClipboardHistory()
        history.add(text("a"))
        history.add(text("b"))
        history.add(text("a"))
        #expect(history.items.compactMap(\.text) == ["a", "b"])
    }

    @Test func theLimitDropsTheOldestButNeverPinned() {
        let history = ClipboardHistory(items: [text("pinned", pinned: true)], limit: 2)
        for word in ["1", "2", "3"] { history.add(text(word)) }
        #expect(history.items.compactMap(\.text) == ["3", "2", "pinned"])
        history.limit = 1
        #expect(history.items.compactMap(\.text) == ["3", "pinned"])
    }

    @Test func aRepeatedPinnedItemStaysPinned() {
        let history = ClipboardHistory(items: [text("keep", pinned: true)])
        history.add(text("keep"))
        #expect(history.items.count == 1 && history.items[0].isPinned)
    }

    @Test func clearingKeepsPinned() {
        let history = ClipboardHistory(items: [text("keep", pinned: true), text("go")])
        history.clear()
        #expect(history.items.compactMap(\.text) == ["keep"])
    }
}

/// Runs against a private pasteboard, never the user's.
@MainActor
@Suite struct ClipboardCaptureTests {
    let pasteboard = NSPasteboard(name: .init("KeyBridgeTests-\(UUID().uuidString)"))
    let defaults: UserDefaults = {
        let suite = "ClipboardCaptureTests.\(UUID().uuidString)"
        return UserDefaults(suiteName: suite)!
    }()
    let store = ClipboardStore(folder: FileManager.default.temporaryDirectory.appending(path: "KeyBridgeTests-\(UUID().uuidString)"))

    func copy(_ text: String, extra: [String] = []) {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for type in extra { item.setData(Data(), forType: .init(type)) }
        pasteboard.writeObjects([item])
    }

    @Test func offByDefaultAndRecordsNothing() {
        let clipboard = ClipboardController(pasteboard: pasteboard, defaults: defaults, store: store)
        #expect(!clipboard.isEnabled)
        copy("hello")
        clipboard.checkNow()
        #expect(clipboard.history.items.isEmpty)

        clipboard.isEnabled = true
        clipboard.checkNow()
        #expect(clipboard.history.items.isEmpty, "Only copies made while it is on")
    }

    @Test func textIsCapturedAndConcealedIsNot() {
        let clipboard = ClipboardController(pasteboard: pasteboard, defaults: defaults, store: store)
        clipboard.isEnabled = true
        copy("hello")
        clipboard.checkNow()
        #expect(clipboard.history.items.first?.text == "hello")

        copy("secret", extra: ["org.nspasteboard.ConcealedType"])
        clipboard.checkNow()
        #expect(!clipboard.history.items.contains { $0.text == "secret" })
    }

    @Test func imagesAndFilesKeepTheirType() throws {
        let clipboard = ClipboardController(pasteboard: pasteboard, defaults: defaults, store: store)
        clipboard.isEnabled = true

        pasteboard.clearContents()
        let image = NSImage(size: NSSize(width: 4, height: 4))
        pasteboard.writeObjects([image])
        clipboard.checkNow()
        #expect(clipboard.history.items.first?.kind == .image)

        pasteboard.clearContents()
        pasteboard.writeObjects([URL(fileURLWithPath: "/tmp/report.pdf") as NSURL])
        clipboard.checkNow()
        #expect(clipboard.history.items.first?.kind == .file)
        #expect(clipboard.history.items.first?.fileURL?.lastPathComponent == "report.pdf")
    }

    @Test func theExclusionListIsEditableAndSaved() {
        let clipboard = ClipboardController(pasteboard: pasteboard, defaults: defaults, store: store)
        clipboard.exclude("com.apple.Safari")
        #expect(ClipboardController(pasteboard: pasteboard, defaults: defaults, store: store).excludedApps.contains("com.apple.Safari"))
        clipboard.include("com.1password.1password")
        #expect(!clipboard.excludedApps.contains("com.1password.1password"))
        clipboard.resetExcludedApps()
        #expect(Set(clipboard.excludedApps) == ClipboardPrivacy.defaultExcludedApps)
    }
}

@MainActor
@Suite struct ClipboardStoreTests {
    let store = ClipboardStore(folder: FileManager.default.temporaryDirectory.appending(path: "KeyBridgeTests-\(UUID().uuidString)"))

    func text(_ string: String, pinned: Bool = false) -> ClipboardItem {
        ClipboardItem(date: .now, contents: [NSPasteboard.PasteboardType.string.rawValue: Data(string.utf8)], isPinned: pinned)
    }

    @Test func historySurvivesARestart() throws {
        let image = ClipboardItem(date: .now, sourceBundleID: "com.apple.Preview",
                                  contents: [NSPasteboard.PasteboardType.png.rawValue: Data([1, 2, 3])])
        let items = [text("b", pinned: true), image, text("a")]
        try store.save(items)
        let loaded = store.load()
        #expect(loaded.map(\.id) == items.map(\.id), "Same order")
        #expect(loaded.map(\.contents) == items.map(\.contents), "Same contents, every type")
        #expect(loaded.first?.isPinned == true)
        #expect(loaded[1].sourceBundleID == "com.apple.Preview")
    }

    @Test func droppedItemsLeaveNoFileBehind() throws {
        let a = text("a"), b = text("b")
        try store.save([a, b])
        try store.save([b])
        let files = try FileManager.default.contentsOfDirectory(atPath: store.folder.appending(path: "items").path)
        #expect(files == ["\(b.id.uuidString).plist"])
    }

    @Test func theFolderIsPrivate() throws {
        try store.save([text("a")])
        let attributes = try FileManager.default.attributesOfItem(atPath: store.folder.path)
        #expect((attributes[.posixPermissions] as? Int) == 0o700)
    }

    @Test func aMissingOrBrokenIndexStartsEmpty() throws {
        #expect(store.load().isEmpty)
        try FileManager.default.createDirectory(at: store.folder, withIntermediateDirectories: true)
        try Data("not json".utf8).write(to: store.folder.appending(path: "index.json"))
        #expect(store.load().isEmpty)
    }

    @Test func theControllerSavesAsItGoes() {
        let history = ClipboardHistory(limit: 2)
        history.onChange = { [store] in try? store.save($0) }
        history.add(text("1"))
        history.add(text("2"))
        history.setPinned(history.items[1].id, true)
        history.add(text("3"))
        history.add(text("4"))
        let loaded = store.load()
        #expect(loaded.compactMap(\.text) == ["4", "3", "1"], "Evicted by the limit, pinned kept")
        #expect(loaded.last?.isPinned == true)
    }
}

@Suite struct ClipboardSearchTests {
    func text(_ string: String, pinned: Bool = false) -> ClipboardItem {
        ClipboardItem(date: .now, contents: [NSPasteboard.PasteboardType.string.rawValue: Data(string.utf8)], isPinned: pinned)
    }

    @Test func everyWordMustAppearInAnyOrderAndCase() {
        let items = [text("SELECT * FROM users"), text("hello world"), text("users of the world")]
        #expect(ClipboardSearch.filter(items, "users select").compactMap(\.text) == ["SELECT * FROM users"])
        #expect(ClipboardSearch.filter(items, "WORLD").count == 2)
        #expect(ClipboardSearch.filter(items, "  ").count == 3, "An empty query shows everything")
    }

    @Test func fileNamesAreSearchedToo() {
        let file = ClipboardItem(date: .now, contents: [
            NSPasteboard.PasteboardType.fileURL.rawValue: Data("file:///tmp/2026Q3-report.pdf".utf8),
        ])
        #expect(ClipboardSearch.filter([file], "report").count == 1)
    }

    @Test func pinnedComeFirst() {
        let items = [text("new"), text("pinned", pinned: true), text("old")]
        #expect(ClipboardSearch.ordered(items).compactMap(\.text) == ["pinned", "new", "old"])
    }
}

@MainActor
@Suite struct ClipboardPanelSupportTests {
    let pasteboard = NSPasteboard(name: .init("KeyBridgeTests-\(UUID().uuidString)"))
    let defaults = UserDefaults(suiteName: "ClipboardPanelSupportTests.\(UUID().uuidString)")!
    let store = ClipboardStore(folder: FileManager.default.temporaryDirectory.appending(path: "KeyBridgeTests-\(UUID().uuidString)"))

    @Test func theShortcutDefaultsToCommandShiftCAndIsSaved() {
        let clipboard = ClipboardController(pasteboard: pasteboard, defaults: defaults, store: store)
        #expect(clipboard.hotKey == KeyCombo([.shift, .command], .c))
        clipboard.setHotKey(KeyCombo([.control, .option], .v))
        #expect(ClipboardController(pasteboard: pasteboard, defaults: defaults, store: store).hotKey
                == KeyCombo([.control, .option], .v))
    }

    @Test func fnIsRejectedForTheShortcut() {
        let hotKey = GlobalHotKey {}
        #expect(throws: GlobalHotKey.Failure.unsupportedModifier) {
            try hotKey.register(KeyCombo([.function], .v))
        }
    }

    @Test func aChosenItemGoesBackInEveryForm() {
        let clipboard = ClipboardController(pasteboard: pasteboard, defaults: defaults, store: store)
        let item = ClipboardItem(date: .now, contents: [
            NSPasteboard.PasteboardType.string.rawValue: Data("hi".utf8),
            NSPasteboard.PasteboardType.rtf.rawValue: Data("{\\rtf1 hi}".utf8),
        ])
        clipboard.restore(item)
        #expect(pasteboard.string(forType: .string) == "hi")
        #expect(pasteboard.data(forType: .rtf) == Data("{\\rtf1 hi}".utf8))
    }
}
